### PR TITLE
Update core-foundation and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/io-surface-rs/62)

### CODE REVIEW

**Comment by Eijebong** [comment]
Not tested, hoped there would be a CI

**Comment by lqd** [comment]
Hello, today I'll be your CI ;) This PR builds on my mac.

**Comment by Eijebong** [comment]
:heart:

**Comment by jdm** [comment]
This repository is deprecated and has been merged with https://github.com/servo/core-foundation-rs/tree/master/io-surface.

**Pull request closed without merging**
