### PR TITLE
Upgrade gleam: 0.1 -> 0.2

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/io-surface-rs/44)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Needed for https://github.com/servo/servo/pull/8761

**Comment by ecoal95** [comment]
@frewsxcv Please update the version number too so it can be published to crates.io.

r? @jdm or someone else?

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/io-surface-rs/44#-:-K5RMFTTn5or6c4QUUK4:1236647940)*

**Comment by ecoal95** [comment]
@metajack I realised this was a servo branch and commited the version number bump too, may you review it again and merge it looks good to you?

(It seems bors is not enabled for this repo)

**Comment by ecoal95** [comment]
r? @metajack 

Fixed the build for latest nightly too (it also works with current servo's rustc).

**Comment by frewsxcv** [comment]
r=frewsxcv your commits, r=Metajack my commit

**Comment by frewsxcv** [comment]
Published

**Comment by metajack** [comment]
Wait, why was this hand merged? If io-surface is not hooked up, please file a bug for that.

**Pull request merged**
