### PR TITLE
Update gleam to v0.4

### LINKED ISSUE #57: Update gleam and cgl to latest version
Updating gleam and cgl is necessary for servo/servo#15781.

### PR DESCRIPTION
**Pull request by sotaroikeda**
Fixes #57.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/io-surface-rs/58)

### CODE REVIEW

**Comment by glennw** [comment]
@sotaroikeda I think the gleam version number should be 0.4 now?

After this one, I *think* the only remaining non-Servo update needed is the ```servo-skia``` package. Are you planning to work on that one too?

**Comment by sotaroikeda** [comment]
@glennw, thanks. I am going to update the pull request. Yes, I am going to work for servo-skia.

**Comment by sotaroikeda** [comment]
@glennw, I updated a patch.

cc @kvark

**Comment by sotaroikeda** [comment]
Can "0.7.0" be published to cargo?

**Comment by KiChjang** [comment]
FTR, I tried to publish this, but ran into problems during compilation, cargo/rustc says it cannot find core_foundation as an external dependency. Perhaps a Mac user is able to publish this instead?

**Comment by glennw** [comment]
@sotaroikeda Published 0.7.0 on crates.io.

@KiChjang You can use ```--no-verify``` as an argument to ```cargo publish``` if you need to publish a mac crate from linux.

**Comment by sotaroikeda** [comment]
Thanks!

**Pull request merged**
